env:
  browser: true
  commonjs: true
  es6: true
  jquery: true
extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/eslint-recommended'
  - 'plugin:@typescript-eslint/recommended'
  - 'prettier'
  - 'prettier/@typescript-eslint'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
plugins:
  - 'prettier'
  - '@typescript-eslint'
rules:
  prettier/prettier:
    - error
    -
      trailingComma: es5
      bracketSpacing: true
      tabWidth: 2
      arrowParens: avoid
      semi: false
      singleQuote: true
      quoteProps: as-needed
      jsxBracketSameLine: true
